# Generated by Django 4.1.4 on 2023-01-28 04:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GuideInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=200, null=True)),
                ('phone', models.IntegerField(unique=True)),
                ('adresss1', models.CharField(blank=True, max_length=200, null=True)),
                ('adresss2', models.CharField(max_length=200)),
                ('province', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7')], default='1')),
                ('profileImage', models.ImageField(blank=True, default='userdp.png', null=True, upload_to='')),
                ('cvFile', models.FileField(upload_to='cv/')),
                ('fbLink', models.CharField(blank=True, max_length=500, null=True)),
                ('instaLink', models.CharField(blank=True, max_length=500, null=True)),
                ('shortIntro', models.CharField(max_length=500)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
