# Generated by Django 4.1.4 on 2023-01-28 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_guideinfo_created_alter_guideinfo_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guideinfo',
            name='shortIntro',
            field=models.TextField(max_length=500),
        ),
    ]
