# Generated by Django 4.1.4 on 2023-01-28 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_guideinfo_shortintro'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guideinfo',
            name='user',
        ),
    ]
