# Generated by Django 4.1.4 on 2023-01-28 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_guideinfo_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guideinfo',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
