# Generated by Django 4.1.4 on 2023-01-28 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_guideinfo_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='guideinfo',
            name='approvedByAdmin',
            field=models.BooleanField(default=False),
        ),
    ]
