# Generated by Django 4.1.4 on 2023-01-28 12:41

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_guideinfo_approvedbyadmin'),
    ]

    operations = [
        migrations.CreateModel(
            name='guideNoti',
            fields=[
                ('approved', models.BooleanField(default=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('guide', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='users.guideinfo')),
            ],
        ),
    ]
