# Generated by Django 4.1.4 on 2023-01-28 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_guidenoti_guide'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guidenoti',
            name='guide',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='users.guideinfo'),
        ),
    ]
