# Generated by Django 4.1.4 on 2023-02-14 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_guideinfo_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guideinfo',
            name='shortIntro',
            field=models.TextField(max_length=100),
        ),
    ]
