# Generated by Django 4.1.1 on 2022-12-12 13:31

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('location', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=200)),
                ('pkLength', models.IntegerField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('uuid', models.UUIDField(default=uuid.uuid5, editable=False, primary_key=True, serialize=False, unique=True)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('vote_total', models.IntegerField(blank=True, default=0, null=True)),
                ('ratings', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
    ]
