# Generated by Django 4.1.1 on 2022-12-12 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Project',
            new_name='Package',
        ),
    ]
