# Generated by Django 4.1.4 on 2022-12-31 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0003_package_featured_img_alter_package_uuid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='package',
            old_name='pkLength',
            new_name='packageDuration',
        ),
        migrations.RenameField(
            model_name='package',
            old_name='location',
            new_name='packageName',
        ),
        migrations.RemoveField(
            model_name='package',
            name='title',
        ),
        migrations.AddField(
            model_name='package',
            name='description',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='package',
            name='itenary',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
