# Generated by Django 4.1.4 on 2022-12-31 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0004_rename_pklength_package_packageduration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='it',
            field=models.JSONField(default=''),
        ),
    ]
