# Generated by Django 4.1.4 on 2023-01-01 14:05

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0006_remove_package_itenary_package_isunderrated_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Packages',
            fields=[
                ('packageName', models.CharField(max_length=100)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('description', models.TextField(blank=True, max_length=2000, null=True)),
                ('packageDuration', models.IntegerField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('vote_total', models.IntegerField(blank=True, default=0, null=True)),
                ('ratings', models.IntegerField(blank=True, default=0, null=True)),
                ('featured_img', models.ImageField(blank=True, default='default.jpg', null=True, upload_to='')),
                ('itenary', models.JSONField(default={'itenary': []})),
                ('isUnderRated', models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='Package',
        ),
    ]
