# Generated by Django 4.1.4 on 2023-01-02 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0007_packages_delete_package'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packages',
            name='itenary',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
