# Generated by Django 4.1.4 on 2023-01-23 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0009_remove_packages_featured_img_images'),
    ]

    operations = [
        migrations.CreateModel(
            name='newp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('newp', models.TextField(max_length=100)),
            ],
        ),
    ]
