# Generated by Django 4.1.4 on 2023-01-23 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0010_newp'),
    ]

    operations = [
        migrations.DeleteModel(
            name='newp',
        ),
    ]
