# Generated by Django 4.1.4 on 2023-01-23 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0011_delete_newp'),
    ]

    operations = [
        migrations.AddField(
            model_name='packages',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
