# Generated by Django 4.1.4 on 2023-01-23 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0012_packages_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='packages',
            name='defimage',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to=''),
        ),
    ]
