# Generated by Django 4.1.4 on 2023-01-26 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0013_packages_defimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packages',
            name='defimage',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
