# Generated by Django 4.1.4 on 2023-01-26 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0014_alter_packages_defimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packages',
            name='defimage',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to=''),
        ),
    ]
