# Generated by Django 4.1.4 on 2023-01-29 15:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('packages', '0015_alter_packages_defimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackageBooking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('packageStartDate', models.DateTimeField(auto_now_add=True)),
                ('packageEndDate', models.DateTimeField(auto_now_add=True)),
                ('peopleAmt', models.IntegerField()),
                ('totalPrice', models.IntegerField()),
                ('packageName', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='packages.packages')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='packagaBookedpeople',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=100)),
                ('lastName', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Others', 'Others')], default='Male', max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.IntegerField()),
                ('PackageBooking', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='packages.packagebooking')),
            ],
        ),
    ]
