# Generated by Django 4.1.4 on 2023-02-12 04:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('packages', '0016_packagebooking_packagabookedpeople'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packagabookedpeople',
            name='PackageBooking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='packages.packagebooking'),
        ),
        migrations.AlterField(
            model_name='packagebooking',
            name='packageName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='packages.packages'),
        ),
        migrations.AlterField(
            model_name='packagebooking',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
